name: minimal c++ compile

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile
        run: g++ test.c++ -o test

      - name: Run
        run: ./test
      
      - name: Remove test binary
        run: rm -f test
